trigger:
  branches:
    include:
      - main  # Override this variable in Azure DevOps to specify the branch

variables:
  - name: branch
    value: 'main'  # Default value, can be overridden during pipeline run
  - name: pantheon-branch
    value: 'main'  # Default value, can be overridden during pipeline run
  - name: vmImageName
    value: 'ubuntu-latest'

pool:
  name: 'azureagent'

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: BuildAndDeploy
    displayName: 'Build and Deploy'
    steps:
    - checkout: self

    - script: |
        echo "Running build steps..."
        # Add your build commands here
      displayName: 'Build Step'

- stage: DeployToProduction
  displayName: 'Deploy to Production'
  dependsOn: Build
  condition: or(and(succeeded('manual_approval'), or(eq(variables['branch'], 'master'), eq(variables['pantheon-branch'], 'master'))), and(succeeded('auto_deploy'), not(or(eq(variables['branch'], 'master'), eq(variables['pantheon-branch'], 'master')))))

  jobs:
  - job: manual_approval
    displayName: "Manual Approval"
    pool:
      name: 'server'
    condition: or(eq(variables['branch'], 'master'), eq(variables['pantheon-branch'], 'master'))  # Only runs if either branch is 'master'
    steps:
    - task: ManualValidation@0
      inputs:
        instructions: 'Deployment requires manual approval. Please review and approve to continue.'
        onTimeout: 'resume'
        notifyUsers: "sa"
      displayName: 'Manual Intervention for Master Branch Deployment'

  - job: auto_deploy
    displayName: 'Automatic Deployment'
    pool:
      vmImage: $(vmImageName)
    condition: and(succeededOrFailed('BuildAndDeploy'), not(or(eq(variables['branch'], 'master'), eq(variables['pantheon-branch'], 'master'))))  # Only runs if neither branch is 'master'
    steps:
    - script: |
        echo "Running automatic deployment steps for non-master branch..."
        # Add your automatic deployment commands here
      displayName: 'Automatic Deployment Step'

  - job: deploy_to_production
    displayName: 'Deploy to Production'
    dependsOn: [manual_approval, auto_deploy]
    condition: or(and(succeeded('manual_approval'), or(eq(variables['branch'], 'master'), eq(variables['pantheon-branch'], 'master'))), and(succeeded('auto_deploy'), not(or(eq(variables['branch'], 'master'), eq(variables['pantheon-branch'], 'master')))))
    pool:
      vmImage: $(vmImageName)
    steps:
    - script: |
        echo "Deploying to Production..."
      displayName: 'Deployment Step'
