trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: BuildAndDeploy
    displayName: 'Build and Deploy'
    steps:
    - checkout: self

    - script: |
        echo "Running build steps..."
        # Add your build commands here
      displayName: 'Build Step'

- stage: DeployToProduction
  displayName: 'Deploy to Production'
  dependsOn: Build
  condition: eq(variables['Build.Reason'], 'Manual') # This ensures manual approval for manual runs
  jobs:
  - deployment: Deploy
    displayName: 'Deploy to Production'
    environment: 'main-dev' # Use your environment name here
    strategy:
      runOnce:
        preDeploy:
          steps:
          - script: echo "Pre-deployment steps..."
            displayName: 'Pre-Deployment Step'
        deploy:
          steps:
          - script: echo "Running deployment steps..."
            displayName: 'Deployment Step'
        
