trigger:
- none

variables:
  branch: 'main'  # Adjust this according to how you pass or set the branch variable
  pantheon_branch: 'main'  # Adjust this according to how you pass or set the pantheon_branch variable

stages:
- stage: Build
  displayName: Build Stage
  jobs:
  - job: BuildJob
    pool:
      name: 'azureagent'
    steps:
    - script: echo Building...
      displayName: 'Build Step'

- stage: Deploy
  displayName: Deploy Stage
  dependsOn: Build
  condition: and(succeeded(), eq(variables['branch'], 'main'), eq(variables['pantheon_branch'], 'main'))
  jobs:
  - job: ManualApproval
    displayName: 'Manual Approval Job'
    pool:
      name: 'server'
    steps:
    - task: ManualValidation@0
      inputs:
        instructions: 'Deployment requires manual approval. Please review and approve to continue.'
        onTimeout: 'resume'
        notifyUsers: "sa@example.com"
      displayName: 'Request Approval for Deployment'

  - job: DeployJob
    displayName: 'Deployment Job'
    dependsOn: ManualApproval
    condition: succeeded('ManualApproval')
    pool:
      name: 'azureagent'  # Use the appropriate pool if you need to switch back for deployment
    steps:
    - script: echo Deploying...
      displayName: 'Deploy Step'

- stage: DeployNoApproval
  displayName: Deploy Without Approval Stage
  dependsOn: Build
  condition: and(succeeded(), not(and(eq(variables['branch'], 'main'), eq(variables['pantheon_branch'], 'main'))))
  jobs:
  - job: DeployJobNoApproval
    displayName: 'Deployment Job Without Approval'
    pool:
      name: 'azureagent'
    steps:
    - script: echo Deploying without approval...
      displayName: 'Deploy Step'
