trigger:
  branches:
    include:
      - main

variables:
  - name: branch
    value: 'master'
  - name: pantheon-branch
    value: 'master'
  - name: vmImageName
    value: 'ubuntu-latest'

pool:
  name: 'azureagent'

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: BuildAndDeploy
    displayName: 'Build and Deploy'
    steps:
    - checkout: self

    - script: |
        echo "Running build steps..."
      displayName: 'Build Step'

- stage: DeployToProduction
  displayName: 'Deploy to Production'
  dependsOn: Build
  condition: succeeded('BuildAndDeploy')

  jobs:
  - job: manual_approval
    displayName: "Manual Approval"
    pool:
      name: 'server'
    condition: and(eq(variables['branch'], 'main'), eq(variables['pantheon-branch'], 'main'))
    steps:
    - task: ManualValidation@0
      inputs:
        instructions: 'Deployment requires manual approval. Please review and approve to continue.'
        onTimeout: 'resume'
        notifyUsers: "sa"
      displayName: 'Manual Intervention for Main Branch Deployment'

  - job: auto_deploy
    displayName: 'Automatic Deployment'
    pool:
      vmImage: $(vmImageName)
    condition: and(not(eq(variables['branch'], 'main')), not(eq(variables['pantheon-branch'], 'main')))
    steps:
    - script: |
        echo "Running automatic deployment steps for non-main branch..."
      displayName: 'Automatic Deployment Step'

  - job: deploy_to_production
    displayName: 'Deploy to Production'
    dependsOn: [manual_approval, auto_deploy]
    condition: or(succeeded('manual_approval'), succeeded('auto_deploy'))
    pool:
      vmImage: $(vmImageName)
    steps:
    - script: |
        echo "Deployment to production completed."
      displayName: 'Deployment to Production Step'
