trigger:
  branches:
    include:
      - main  # Or the branch you want to use as the trigger

pool:
  name: 'azureagent'

variables:
  - name: branch
    value: 'main'  # Default value, can be overridden during pipeline run
  - name: pantheon-branch
    value: 'main'  # Default value, can be overridden during pipeline run

stages:
  - stage: Build
    displayName: 'Build Stage'
    jobs:
      - job: BuildAndDeploy
        displayName: 'Build and Deploy'
        steps:
          - checkout: self

          - script: |
              echo "Running build steps..."
              # Add your build commands here
            displayName: 'Build Step'

  - stage: DeployToProduction
    displayName: 'Deploy to Production'
    dependsOn: Build
    condition: or(
      eq(variables['branch'], 'master'),
      eq(variables['pantheon-branch'], 'master')
    )
    jobs:
      - job: manual_approval
        displayName: "Manual Approval"
        pool:
          name: 'server'
        steps:
          - task: ManualValidation@0
            timeoutInMinutes: 5
            inputs:
              instructions: "Deployment requires manual approval. Please review and approve to continue."
              notifyUsers: 'sarthakpokhrel3@gmail.com'
              onTimeout: 'reject'  # Or 'resume' based on your requirement
            displayName: 'Manual Approval Step'

      - deployment: DeployToProduction
        displayName: 'Deploy to Production'
        dependsOn: manual_approval
        environment: 'main-dev'  # Your environment name
        strategy:
          runOnce:
            deploy:
              steps:
                - script: echo "Running deployment steps..."
                  displayName: 'Deployment Step'
