trigger:
- none

variables:
  branch: '$(Build.SourceBranchName)'  # Adjust this according to how you pass or set the branch variable
  pantheon_branch: '$(PantheonBranch)'  # Adjust this according to how you pass or set the pantheon_branch variable

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - script: echo Building...
      displayName: 'Build Step'

- stage: Deploy
  dependsOn: Build
  condition: and(succeeded(), eq(variables['branch'], 'main'), eq(variables['pantheon_branch'], 'main'))
  jobs:
  - job: manual_approval
    displayName: "Manual Approval"
    pool:
      name: 'server'
    steps:
    - task: ManualValidation@0
      inputs:
        instructions: 'Deployment requires manual approval. Please review and approve to continue.'
        onTimeout: 'resume'
        notifyUsers: "sa@example.com"
      displayName: 'Manual Intervention for Main Branch Deployment'

  - job: DeployJob
    dependsOn: manual_approval
    condition: and(succeeded(), eq(variables['branch'], 'main'), eq(variables['pantheon_branch'], 'main'))
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: echo Deploying to main branch...
      displayName: 'Deploy Step'

- stage: DeployNoApproval
  dependsOn: Build
  condition: and(succeeded(), not(and(eq(variables['branch'], 'main'), eq(variables['pantheon_branch'], 'main'))))
  jobs:
  - job: DeployJobNoApproval
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: echo Deploying without approval...
      displayName: 'Deploy Step'
