trigger:
  branches:
    include:
      - main

pool:
  name: 'azureagent'

jobs:
- job: BuildAndDeploy
  displayName: 'Build and Deploy with Confirmation for Master Branch'
  steps:
  - checkout: self

  - script: |
      sudo apt-get update
      sudo apt-get install -y wget apt-transport-https software-properties-common
      wget -q https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
      sudo dpkg -i packages-microsoft-prod.deb
      sudo apt-get update
      sudo apt-get install -y powershell
    displayName: 'Install PowerShell Core'

  - script: |
      echo "Running build steps..."
      # Add your build commands here
    displayName: 'Build Step'

  - task: ManualIntervention@0
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
    inputs:
      instructions: 'Deployment to master branch requires manual approval. Please review and approve to continue.'
      onTimeout: 'resume'
      timeout: '1d'
    displayName: 'Manual Intervention for Master Branch Deployment'
